# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsearchskill():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsearchskill(self):
    self.driver.get("http://test.qahunter.ru/")
    self.driver.set_window_size(1616, 876)
    self.driver.find_element(By.ID, "formInput#search").click()
    self.driver.find_element(By.ID, "formInput#search").send_keys("Python")
    self.driver.find_element(By.CSS_SELECTOR, ".btn--lg").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".column:nth-child(3) .tag").text == "Python"
  
